### ISSUE TITLE
seed domains outdated

### ISSUE THREAD

**Issue by cybershambles** [AusDTO/disco_crawl#28]
Hello,

Could I please request the seed domains be updated?

**Comment by monkeypants** [comment]
We currently don't use seed domains the same way anymore - instead, we simply start at australia.gov.au and follow links with "breadth-first" strategy.

Maybe this [big list of gov.au domains](https://github.com/AusDTO/disco_crawl/files/1664095/big_list_of_gov_au_domains.txt) is something like what you are after?

**Comment by cybershambles** [comment]
The australia.gov.au isn't machine readable.

**Comment by monkeypants** [comment]
that csv i attached should be, and has many more domains than australia.gov.au. Do you need something different?
