### ISSUE TITLE
Crawls tel: addresses

### ISSUE THREAD

**Issue by seanhamlin** [AusDTO/disco_crawl#32]
Spotted in the logs (282 times in the last 7 days):

```
... notice 13.210.109.162 - - [28/Jan/2018:21:01:02 +0000] "GET /immunisationfacts/tel:0262052300 HTTP/1.1" 404 17952 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:54.0) https://github.com/AusDTO/disco_crawl" vhost=... host=campaigns.health.gov.au hosting_site=... pid=18283 request_time=370688 forwarded_for="..." request_id="v-59148a2e-046e-11e8-9ae9-22000afb0131"
```

Can you please not crawl URLs that are telephone links?

**Comment by monkeypants** [comment]
Looks like it might be a bug. Thanks!

**Comment by monkeypants** [comment]
just following this up - we deployed the tel: link fixes over a week ago and havent noticed any problems or had any reported. So I think we can close the ticket now.
