### ISSUE TITLE
Problematic sites list

### ISSUE THREAD

**Issue by koriaf** [AusDTO/disco_crawl#37]
* https://domainname.gov.au/ - TLS certificate doesn't include non-www version, while https://www.domainname.gov.au/ works fine

**Comment by monkeypants** [comment]
does the crawler ride over that problem ok? we arent specifically looking at TLS data per domain, although of course that's possible.

**Comment by koriaf** [comment]
yes, crawler either just assumes the https is broken and use http version or user https://www if this is possible here (in this example - yes). And ignores non-www version if www-version is available and non-www don't redirect to www.

**Comment by monkeypants** [comment]
Then I think "no action required" for us, I'll close the ticket.

**Comment by koriaf** [comment]
on australia.gov.au they use something like double escape for JS message:
```
<!-- JS compatibility message -->
  <noscript>&lt;a id="msgNojs" href="http://enable-javascript.com/" target="_blank"&gt;This site requires JavaScript. Click here for instructions on enabling it in your browser&lt;/a&gt;</noscript>
<!-- IE compatibility message -->
```
works for any page. I think the non-escaped <a..> is expected there.
